format = """
$os\
$directory\
$git_branch\
$git_status\
$fill\
$time\
$cmd_duration
$character"""

[os]
format = '[$symbol]($style)'
style = "bold blue"
disabled = false

[os.symbols]
Windows = "󰍲"

[time]
disabled = false
format = '[\[ $time \]]($style) '
time_format = '%F %T'

[cmd_duration]
min_time = 500
format = 'took [$duration](bold yellow)'

[fill]
symbol = " "
style = "bold black"
disabled = false

[sudo]
style = "red"
format = "Admin($style)"
disabled = false

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](bright-black) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"
